import "server-only";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";

/**
 * Where uploaded files live. The rest of the app only talks to this interface,
 * so moving to S3-compatible storage (AWS S3, Cloudflare R2…) for production
 * means adding one driver, not changing pages.
 */
export interface StorageDriver {
  put(key: string, data: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<Buffer | null>;
  remove(key: string): Promise<void>;
}

/** Keys are generated by the app: "<uuid>.<ext>". Anything else is rejected. */
export const STORAGE_KEY_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(png|jpg|webp|gif|pdf)$/;

function assertKey(key: string) {
  if (!STORAGE_KEY_PATTERN.test(key)) throw new Error("Invalid storage key");
}

/** Development driver: files in ./storage/media (git-ignored). */
class LocalDriver implements StorageDriver {
  private root = path.join(process.cwd(), "storage", "media");

  private file(key: string) {
    assertKey(key);
    return path.join(this.root, key);
  }
  async put(key: string, data: Buffer) {
    await mkdir(this.root, { recursive: true });
    await writeFile(this.file(key), data, { flag: "wx" });
  }
  async get(key: string) {
    try {
      return await readFile(this.file(key));
    } catch {
      return null;
    }
  }
  async remove(key: string) {
    await rm(this.file(key), { force: true });
  }
}

let driver: StorageDriver | null = null;

export function storage(): StorageDriver {
  if (driver) return driver;
  const kind = process.env.STORAGE_DRIVER ?? "local";
  if (kind === "local") {
    if (process.env.APP_ENV === "production") {
      console.warn("[storage] Using local disk storage in production. Configure S3-compatible storage before launch.");
    }
    driver = new LocalDriver();
    return driver;
  }
  // The S3 driver is added in the deployment phase (Phase 14).
  throw new Error(`STORAGE_DRIVER="${kind}" is not available yet. Use "local" for now.`);
}
